#!/usr/bin/env zsh
# =============================================================================
# lib/state.zsh — Read/write wizard state
# State is stored as zsh associative arrays + scalars in $STATE_FILE.
# Dependencies: config.zsh
# =============================================================================

# ------------------------------------------------------------------------------
# state_init
# Initialize empty in-memory state. Call this before the wizard runs.
# ------------------------------------------------------------------------------
state_init() {
  typeset -gA APP_DEST          # appid → "goinfree" | "session" | "skip"
  typeset -gA APP_RECOMMENDED   # appid → recommended dest (read from manifest)

  # Feature flags
  FEAT_VENCORD=false
  FEAT_DARKMODE=false
  FEAT_FIREFOX_PROFILE=false
  FEAT_FIREFOX_DOWNGRADE=false
  FEAT_PYTHON_VSCODE=false
  FEAT_NVCHAD=false
}

# ------------------------------------------------------------------------------
# state_save
# Persist current state to $STATE_FILE.
# ------------------------------------------------------------------------------
state_save() {
  mkdir -p "$SETUP_HOME"

  {
    print "#!/usr/bin/env zsh"
    print "# Generated by mac-setup wizard — do not edit by hand"
    print ""
    print "typeset -gA APP_DEST"
    for key val in ${(kv)APP_DEST}; do
      print "APP_DEST[$key]=\"$val\""
    done
    print ""
    print "FEAT_VENCORD=$FEAT_VENCORD"
    print "FEAT_DARKMODE=$FEAT_DARKMODE"
    print "FEAT_FIREFOX_PROFILE=$FEAT_FIREFOX_PROFILE"
    print "FEAT_FIREFOX_DOWNGRADE=$FEAT_FIREFOX_DOWNGRADE"
    print "FEAT_PYTHON_VSCODE=$FEAT_PYTHON_VSCODE"
    print "FEAT_NVCHAD=$FEAT_NVCHAD"
  } > "$STATE_FILE"
}

# ------------------------------------------------------------------------------
# state_load
# Source $STATE_FILE into the current shell. Returns 1 if file doesn't exist.
# ------------------------------------------------------------------------------
state_load() {
  [[ ! -f "$STATE_FILE" ]] && return 1
  state_init
  source "$STATE_FILE"
  return 0
}

# ------------------------------------------------------------------------------
# state_populate_recommendations
# Read each app's recommended_dest from the manifest into APP_RECOMMENDED.
# Also sets APP_DEST to the recommended value as a starting point.
# ------------------------------------------------------------------------------
state_populate_recommendations() {
  for app_id in $(install_list_app_ids); do
    local rec
    rec=$(install_get_manifest_field "$app_id" "recommended_dest")
    [[ -z "$rec" ]] && rec="goinfree"
    APP_RECOMMENDED[$app_id]=$rec
    APP_DEST[$app_id]=$rec
  done
}

# ------------------------------------------------------------------------------
# state_dest_for <app_id>
# Print the current destination for an app (goinfree/session/skip).
# ------------------------------------------------------------------------------
state_dest_for() {
  print "${APP_DEST[$1]:-skip}"
}

# ------------------------------------------------------------------------------
# state_cycle_app <app_id>
# Cycle an app's placement: goinfree → session → skip → goinfree
# ------------------------------------------------------------------------------
state_cycle_app() {
  local app_id=$1
  case "${APP_DEST[$app_id]}" in
    goinfree) APP_DEST[$app_id]="session"  ;;
    session)  APP_DEST[$app_id]="skip"     ;;
    *)        APP_DEST[$app_id]="goinfree" ;;
  esac
}

# ------------------------------------------------------------------------------
# state_reset_to_recommended
# Set all APP_DEST entries back to their recommended values.
# ------------------------------------------------------------------------------
state_reset_to_recommended() {
  for app_id in ${(k)APP_RECOMMENDED}; do
    APP_DEST[$app_id]=${APP_RECOMMENDED[$app_id]}
  done
}
